apiVersion: v1
kind: Service
metadata:
  name: b-emailservice
spec:
  ports:
    - name: c-http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: b-emailservice
  type: LoadBalancer
